import type { AllOrder } from "@/lib/tableTypes"

export const mockOrders: AllOrder[] = [
  {
    id: "ORD-2024-001",
    vendor: "Rajesh Kumar",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹2,499",
    status: "Canceled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "20 Jun 2025",
    returnStatus: "Return Requested",
    productList: [
      {
        name: "Tommy Hilfiger Men Striped Polo Collar Cotton T-shirt",
        quantity: 1,
        price: 100,
      },
    ],
  },
  {
    id: "ORD-2024-002",
    vendor: "Priya Sharma",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹3,547.36",
    status: "Pending",
    paymentStatus: "Pending",
    type: "B2B",
    inventoryType: "sale_or_return",
    delivery: "21 Jun 2025",
    returnStatus: "Return Requested",
    productList: [
      { name: "Cotton Kurta Set", price: 1799, quantity: 1 },
      { name: "Linen Dupatta", price: 899, quantity: 2 },
    ],
  },
  {
    id: "ORD-2024-003",
    vendor: "ABC Retailers Pvt Ltd",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹20,764",
    status: "Pending",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "22 Jun 2025",
    returnStatus: "Approved",
    productList: [{ name: "Wholesale Kurti Pack (12 pc)", price: 1730, quantity: 12 }],
  },
  {
    id: "ORD-2024-004",
    vendor: "XYZ Industries",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹9,285.48",
    status: "Pending",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "stock_clearance",
    delivery: "23 Jun 2025",
    returnStatus: "Return Requested",
    productList: [
      { name: "Women Kurti Set", quantity: 5, price: 1499 },
      { name: "Dupatta - Maroon", quantity: 5, price: 399 },
    ],
  },
  {
    id: "ORD-2024-005",
    vendor: "Anita Desai",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹1,499",
    status: "Canceled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "24 Jun 2025",
    returnStatus: "Completed",
    productList: [
      { name: "Casual Tee", quantity: 2, price: 499 },
    ],
  },
  {
    id: "ORD-2024-006",
    vendor: "Ram Singh Chauhan",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹80,956",
    status: "Pending",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "25 Jun 2025",
    returnStatus: "Approved",
    productList: [
      { name: "Hoodie - Black", quantity: 3, price: 1599 },
      { name: "Joggers - Grey", quantity: 3, price: 1199 },
    ],
  },
  {
    id: "ORD-2024-007",
    vendor: "Vaibhav Bhatnagar",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹42,680",
    status: "Completed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "26 Jun 2025",
    returnStatus: "Completed",
    productList: [
      { name: "Denim Jacket", quantity: 12, price: 2199 },
    ],
  },
  {
    id: "ORD-2024-008",
    vendor: "Vaibhav Bhatnagar",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹42,680",
    status: "Returned",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "pre_booking",
    delivery: "26 Jun 2025",
    returnStatus: "Return Requested",
    productList: [
      { name: "Printed Polo T-Shirt", quantity: 9, price: 899 },
      { name: "Chino Pants", quantity: 9, price: 1499 },
    ],
  },
  {
    id: "ORD-2024-009",
    vendor: "Vaibhav Bhatnagar",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹42,680",
    status: "Completed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "sale_or_return",
    delivery: "26 Jun 2025",
    returnStatus: "Approved",
    productList: [
      { name: "Classic Saree", quantity: 7, price: 2499 },
      { name: "Silk Blouse Piece", quantity: 7, price: 699 },
    ],
  },
  {
    id: "ORD-2026-010",
    vendor: "Meera Textiles Wholesale",
    date: "02 Apr 2026, 9:15 am",
    amount: "₹56,230",
    status: "Completed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "stock_clearance",
    delivery: "08 Apr 2026",
    returnStatus: "Completed",
    productList: [
      { name: "Wholesale Linen Shirts", quantity: 20, price: 1899 },
      { name: "Office Wear Trousers", quantity: 15, price: 1599 },
    ],
  },
  {
    id: "ORD-2026-011",
    vendor: "Urban Style Co.",
    date: "03 Apr 2026, 2:40 pm",
    amount: "₹3,890",
    status: "Processing",
    paymentStatus: "Pending",
    type: "B2C",
    delivery: "10 Apr 2026",
    returnStatus: "Completed",
    productList: [
      { name: "Graphic Tee", price: 1299, quantity: 2 },
      { name: "Denim Jacket", price: 292, quantity: 1 },
    ],
  },
  {
    id: "ORD-2026-012",
    vendor: "Northwind Apparel Ltd",
    date: "04 Apr 2026, 11:05 am",
    amount: "₹1,12,450",
    status: "Pending",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "12 Apr 2026",
    returnStatus: "Completed",
    productList: [
      { name: "Institutional Uniform Set", quantity: 40, price: 2299 },
      { name: "Name Patch Bundle", quantity: 40, price: 149 },
    ],
  },
  {
    id: "ORD-2026-013",
    vendor: "Kiran Patel",
    date: "05 Apr 2026, 8:22 am",
    amount: "₹2,150",
    status: "Delivered",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "09 Apr 2026",
    productList: [
      { name: "Summer Dress", quantity: 1, price: 2150 },
    ],
  },
  {
    id: "ORD-2026-014",
    vendor: "Luxe Garments Export",
    date: "06 Apr 2026, 4:50 pm",
    amount: "₹88,900",
    status: "Canceled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "sale_or_return",
    delivery: "—",
    returnStatus: "Completed",
    productList: [
      { name: "Export Quality Suit Set", quantity: 18, price: 4899 },
    ],
  },
  {
    id: "ORD-2026-015",
    vendor: "Streetwear Collective",
    date: "07 Apr 2026, 1:18 pm",
    amount: "₹6,799",
    status: "Shipped",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "14 Apr 2026",
    productList: [
      { name: "Graphic Hoodie", quantity: 2, price: 1899 },
      { name: "Beanie Cap", quantity: 1, price: 499 },
    ],
  },
  {
    id: "ORD-2026-016",
    vendor: "Institutional Supplies Inc.",
    date: "08 Apr 2026, 10:00 am",
    amount: "₹2,45,000",
    status: "Completed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "18 Apr 2026",
    productList: [
      { name: "Bulk Safety Jackets", quantity: 60, price: 2499 },
      { name: "Reflective Trousers", quantity: 60, price: 1584 },
    ],
  },
  {
    id: "ORD-2026-017",
    vendor: "Sneha Reddy",
    date: "09 Apr 2026, 3:33 pm",
    amount: "₹1,299",
    status: "Canceled",
    paymentStatus: "Pending",
    type: "B2C",
    delivery: "—",
    productList: [
      { name: "Cotton Top", quantity: 1, price: 1299 },
    ],
  },
  {
    id: "ORD-2026-018",
    vendor: "Metro Fashion Hub",
    date: "10 Apr 2026, 9:45 am",
    amount: "₹34,560",
    status: "Pending",
    paymentStatus: "Pending",
    type: "B2B",
    inventoryType: "stock_clearance",
    delivery: "20 Apr 2026",
    productList: [
      { name: "Retail Display Shirts", quantity: 14, price: 1599 },
      { name: "Store Staff Tees", quantity: 14, price: 869 },
    ],
  },
  {
    id: "ORD-2026-019",
    vendor: "Arjun Mehta",
    date: "11 Apr 2026, 6:10 pm",
    amount: "₹4,450",
    status: "Completed",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "15 Apr 2026",
    productList: [
      { name: "Casual Denim Jeans", quantity: 1, price: 4450 },
    ],
  },
  {
    id: "ORD-2026-020",
    vendor: "BulkBuy Traders",
    date: "12 Apr 2026, 12:30 pm",
    amount: "₹67,200",
    status: "Pending",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "22 Apr 2026",
    productList: [
      { name: "Warehouse Polo Pack", quantity: 25, price: 1799 },
      { name: "Workwear Cargo Pants", quantity: 20, price: 1111 },
    ],
  },
  {
    id: "ORD-2026-021",
    vendor: "EcoWear Studio",
    date: "13 Apr 2026, 7:55 am",
    amount: "₹5,120",
    status: "Returned",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "17 Apr 2026",
    returnStatus: "Return Requested",
    productList: [
      { name: "Organic Cotton Kurta", quantity: 1, price: 3120 },
      { name: "Handloom Dupatta", quantity: 1, price: 2000 },
    ],
  },
  {
    id: "ORD-2026-022",
    vendor: "Pan India Distributors",
    date: "14 Apr 2026, 2:15 pm",
    amount: "₹1,89,750",
    status: "Pending",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "pre_booking",
    delivery: "25 Apr 2026",
    returnStatus: "Approved",
    productList: [
      { name: "Distributor Premium Combo", quantity: 32, price: 3999 },
      { name: "Seasonal Promo Tees", quantity: 32, price: 1930 },
    ],
  },
  {
    id: "ORD-2026-023",
    vendor: "Riya Kapoor",
    date: "14 Apr 2026, 5:40 pm",
    amount: "₹899",
    status: "Partial Fulfillment",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "18 Apr 2026",
    productList: [
      { name: "Floral Top", quantity: 1, price: 899 },
    ],
  },
  {
    id: "ORD-2026-024",
    vendor: "Southern Traders Consortium",
    date: "15 Apr 2026, 10:30 am",
    amount: "₹50,499",
    status: "Shipped",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "22 Apr 2026",
    productList: [
      { name: "Bulk Knit Sweaters", quantity: 48, price: 899 },
      { name: "Merchandising Hangers Pack", quantity: 10, price: 499 },
    ],
  },
  {
    id: "ORD-2026-025",
    vendor: "Heritage Mills Pvt Ltd",
    date: "16 Apr 2026, 11:00 am",
    amount: "₹53,548",
    status: "Partial Fulfillment",
    paymentStatus: "Pending",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "28 Apr 2026",
    productList: [
      { name: "Industrial Yarn Bundle", quantity: 120, price: 1899 },
      { name: "Loom Fabric Rolls", quantity: 80, price: 1499 },
    ],
  },
  {
    id: "ORD-2026-026",
    vendor: "Pacific Apparel Distributors",
    date: "17 Apr 2026, 3:15 pm",
    amount: "₹8,92,340",
    status: "Processing",
    paymentStatus: "Pending",
    type: "B2B",
    inventoryType: "pre_booking",
    delivery: "05 May 2026",
    productList: [
      { name: "Season Pre-Order Jackets", quantity: 200, price: 3299 },
      { name: "Corporate Logo Tees", quantity: 200, price: 1150 },
    ],
  },
  {
    id: "ORD-2026-027",
    vendor: "Metro Wholesale Exchange",
    date: "18 Apr 2026, 9:00 am",
    amount: "₹2,04,150",
    status: "Delivered",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "stock_clearance",
    delivery: "12 Apr 2026",
    productList: [
      { name: "End-of-Season Kurtis", quantity: 90, price: 1499 },
    ],
  },
]
