import type { AllOrder } from "@/lib/tableTypes";

export const mockOrders: AllOrder[] = [
  {
    id: "ORD-2024-001",
    vendor: "Rajesh Kumar",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹2,499",
    status: "Cancelled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "20 Jun 2025",
    returnStatus: "Pending",
    productList: [
      {
        name: "Tommy Hilfiger Men Striped Polo Collar Cotton T-shirt",
        quantity: 1,
        price: 100,
      },
    ],
  },
  {
    id: "ORD-2024-002",
    vendor: "Priya Sharma",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹3,547.36",
    status: "Unconfirmed",
    paymentStatus: "Pending",
    type: "B2B",
    inventoryType: "sale_or_return",
    delivery: "21 Jun 2025",
    returnStatus: "Pending",
    productList: [
      { name: "Cotton Kurta Set", price: 1799, quantity: 1 },
      { name: "Linen Dupatta", price: 899, quantity: 2 },
    ],
  },
  {
    id: "ORD-2024-003",
    vendor: "ABC Retailers Pvt Ltd",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹20,764",
    status: "Unconfirmed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "22 Jun 2025",
    returnStatus: "Approved",
    productList: [{ name: "Wholesale Kurti Pack (12 pc)", price: 1730, quantity: 12 }],
  },
  {
    id: "ORD-2024-004",
    vendor: "XYZ Industries",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹9,285.48",
    status: "Unconfirmed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "stock_clearance",
    delivery: "23 Jun 2025",
    returnStatus: "Pending",
    productList: [
      { name: "Women Kurti Set", quantity: 5, price: 1499 },
      { name: "Dupatta - Maroon", quantity: 5, price: 399 },
    ],
  },
  {
    id: "ORD-2026-025",
    vendor: "Heritage Mills Pvt Ltd",
    date: "16 Apr 2026, 11:00 am",
    amount: "₹53,548",
    status: "Partially Fulfilled",
    partial_fulfillment_status: "not_fulfilled",
    partial_fulfillment_quantities: {
      total: 60,
      fulfilled: 0,
      delivered: 0,
      pending: 60,
    },
    paymentStatus: "Pending",
    type: "B2B",
    inventoryType: "pre_booking",
    delivery: "28 Apr 2026",
    productList: [
      { name: "Industrial Yarn Bundle", quantity: 120, price: 1899 },
      { name: "Loom Fabric Rolls", quantity: 80, price: 1499 },
    ],
  },
  {
    id: "ORD-2024-005",
    vendor: "Anita Desai",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹1,499",
    status: "Cancelled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "24 Jun 2025",
    returnStatus: "QC Passed",
    productList: [{ name: "Casual Tee", quantity: 2, price: 499 }],
  },
  {
    id: "ORD-2024-006",
    vendor: "Ram Singh Chauhan",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹80,956",
    status: "Unconfirmed",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "25 Jun 2025",
    returnStatus: "Approved",
    productList: [
      { name: "Hoodie - Black", quantity: 3, price: 1599 },
      { name: "Joggers - Grey", quantity: 3, price: 1199 },
    ],
  },
  {
    id: "ORD-2024-007",
    vendor: "Vaibhav Bhatnagar",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹42,680",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "26 Jun 2025",
    returnStatus: "QC Passed",
    productList: [{ name: "Denim Jacket", quantity: 12, price: 2199 }],
  },
  {
    id: "ORD-2024-008",
    vendor: "Vaibhav Bhatnagar",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹42,680",
    status: "Fulfilled",
    partial_fulfillment_status: "fully_fulfilled",
    partial_fulfillment_quantities: {
      total: 18,
      fulfilled: 18,
      delivered: 18,
      pending: 0,
    },
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "pre_booking",
    delivery: "26 Jun 2025",
    returnStatus: "Pending",
    productList: [
      { name: "Printed Polo T-Shirt", quantity: 9, price: 899 },
      { name: "Chino Pants", quantity: 9, price: 1499 },
    ],
  },
  {
    id: "ORD-2024-009",
    vendor: "Vaibhav Bhatnagar",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹42,680",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "sale_or_return",
    delivery: "26 Jun 2025",
    returnStatus: "Approved",
    productList: [
      { name: "Classic Saree", quantity: 7, price: 2499 },
      { name: "Silk Blouse Piece", quantity: 7, price: 699 },
    ],
  },
  {
    id: "ORD-2026-010",
    vendor: "Meera Textiles Wholesale",
    date: "02 Apr 2026, 9:15 am",
    amount: "₹56,230",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "stock_clearance",
    delivery: "08 Apr 2026",
    returnStatus: "QC Passed",
    productList: [
      { name: "Wholesale Linen Shirts", quantity: 20, price: 1899 },
      { name: "Office Wear Trousers", quantity: 15, price: 1599 },
    ],
  },
  {
    id: "ORD-2026-011",
    vendor: "Urban Style Co.",
    date: "03 Apr 2026, 2:40 pm",
    amount: "₹3,890",
    status: "Unfulfilled",
    paymentStatus: "Pending",
    type: "B2C",
    delivery: "10 Apr 2026",
    returnStatus: "QC Passed",
    productList: [
      { name: "Graphic Tee", price: 1299, quantity: 2 },
      { name: "Denim Jacket", price: 292, quantity: 1 },
    ],
  },
  {
    id: "ORD-2026-012",
    vendor: "Northwind Apparel Ltd",
    date: "04 Apr 2026, 11:05 am",
    amount: "₹1,12,450",
    status: "Unconfirmed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "12 Apr 2026",
    returnStatus: "QC Passed",
    productList: [
      { name: "Institutional Uniform Set", quantity: 40, price: 2299 },
      { name: "Name Patch Bundle", quantity: 40, price: 149 },
    ],
  },
  {
    id: "ORD-2026-013",
    vendor: "Kiran Patel",
    date: "05 Apr 2026, 8:22 am",
    amount: "₹2,150",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "09 Apr 2026",
    productList: [{ name: "Summer Dress", quantity: 1, price: 2150 }],
  },
  {
    id: "ORD-2026-014",
    vendor: "Luxe Garments Export",
    date: "06 Apr 2026, 4:50 pm",
    amount: "₹88,900",
    status: "Cancelled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "sale_or_return",
    delivery: "—",
    returnStatus: "QC Passed",
    productList: [
      { name: "Export Quality Suit Set", quantity: 18, price: 4899 },
    ],
  },
  {
    id: "ORD-2026-015",
    vendor: "Streetwear Collective",
    date: "07 Apr 2026, 1:18 pm",
    amount: "₹6,799",
    status: "Partially Fulfilled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "14 Apr 2026",
    productList: [
      { name: "Graphic Hoodie", quantity: 2, price: 1899 },
      { name: "Beanie Cap", quantity: 1, price: 499 },
    ],
  },
  {
    id: "ORD-2026-016",
    vendor: "Institutional Supplies Inc.",
    date: "08 Apr 2026, 10:00 am",
    amount: "₹2,45,000",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "18 Apr 2026",
    productList: [
      { name: "Bulk Safety Jackets", quantity: 60, price: 2499 },
      { name: "Reflective Trousers", quantity: 60, price: 1584 },
    ],
  },
  {
    id: "ORD-2026-017",
    vendor: "Sneha Reddy",
    date: "09 Apr 2026, 3:33 pm",
    amount: "₹1,299",
    status: "Cancelled",
    paymentStatus: "Pending",
    type: "B2C",
    delivery: "—",
    productList: [{ name: "Cotton Top", quantity: 1, price: 1299 }],
  },
  {
    id: "ORD-2026-018",
    vendor: "Metro Fashion Hub",
    date: "10 Apr 2026, 9:45 am",
    amount: "₹34,560",
    status: "Unconfirmed",
    paymentStatus: "Pending",
    type: "B2B",
    inventoryType: "stock_clearance",
    delivery: "20 Apr 2026",
    productList: [
      { name: "Retail Display Shirts", quantity: 14, price: 1599 },
      { name: "Store Staff Tees", quantity: 14, price: 869 },
    ],
  },
  {
    id: "ORD-2026-019",
    vendor: "Arjun Mehta",
    date: "11 Apr 2026, 6:10 pm",
    amount: "₹4,450",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "15 Apr 2026",
    productList: [{ name: "Casual Denim Jeans", quantity: 1, price: 4450 }],
  },
  {
    id: "ORD-2026-020",
    vendor: "BulkBuy Traders",
    date: "12 Apr 2026, 12:30 pm",
    amount: "₹67,200",
    status: "Unconfirmed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "22 Apr 2026",
    productList: [
      { name: "Warehouse Polo Pack", quantity: 25, price: 1799 },
      { name: "Workwear Cargo Pants", quantity: 20, price: 1111 },
    ],
  },
  {
    id: "ORD-2026-021",
    vendor: "EcoWear Studio",
    date: "13 Apr 2026, 7:55 am",
    amount: "₹5,120",
    status: "Returned",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "17 Apr 2026",
    returnStatus: "Pending",
    productList: [
      { name: "Organic Cotton Kurta", quantity: 1, price: 3120 },
      { name: "Handloom Dupatta", quantity: 1, price: 2000 },
    ],
  },
  {
    id: "ORD-2026-022",
    vendor: "Pan India Distributors",
    date: "14 Apr 2026, 2:15 pm",
    amount: "₹1,89,750",
    status: "Fulfilled",
    partial_fulfillment_status: "fully_fulfilled",
    partial_fulfillment_quantities: {
      total: 64,
      fulfilled: 64,
      delivered: 64,
      pending: 0,
    },
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "pre_booking",
    delivery: "25 Apr 2026",
    returnStatus: "Approved",
    productList: [
      { name: "Distributor Premium Combo", quantity: 32, price: 3999 },
      { name: "Seasonal Promo Tees", quantity: 32, price: 1930 },
    ],
  },
  {
    id: "ORD-2026-024",
    vendor: "Southern Traders Consortium",
    date: "15 Apr 2026, 10:30 am",
    amount: "₹50,499",
    status: "Partially Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "22 Apr 2026",
    productList: [
      { name: "Bulk Knit Sweaters", quantity: 48, price: 899 },
      { name: "Merchandising Hangers Pack", quantity: 10, price: 499 },
    ],
  },
  {
    id: "ORD-2026-026",
    vendor: "Pacific Apparel Distributors",
    date: "17 Apr 2026, 3:15 pm",
    amount: "₹8,92,340",
    status: "Partially Fulfilled",
    partial_fulfillment_status: "partially_fulfilled",
    partial_fulfillment_quantities: {
      total: 75,
      fulfilled: 30,
      delivered: 22,
      pending: 45,
    },
    paymentStatus: "Pending",
    type: "B2B",
    inventoryType: "pre_booking",
    delivery: "05 May 2026",
    productList: [
      { name: "Season Pre-Order Jackets", quantity: 200, price: 3299 },
      { name: "Corporate Logo Tees", quantity: 200, price: 1150 },
    ],
  },
  {
    id: "ORD-2026-031",
    vendor: "Coastal Pre-Order Collective",
    date: "17 Apr 2026, 5:00 pm",
    amount: "₹1,24,800",
    status: "Partially Fulfilled",
    partial_fulfillment_status: "fully_fulfilled",
    partial_fulfillment_quantities: {
      total: 40,
      fulfilled: 40,
      delivered: 40,
      pending: 0,
    },
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "pre_booking",
    delivery: "30 Apr 2026",
    productList: [
      { name: "Pre-Book Uniform Shell Jackets", quantity: 40, price: 2199 },
      { name: "Matching Trousers", quantity: 40, price: 930 },
    ],
  },
  {
    id: "ORD-2026-027",
    vendor: "Metro Wholesale Exchange",
    date: "18 Apr 2026, 9:00 am",
    amount: "₹2,04,150",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "stock_clearance",
    delivery: "12 Apr 2026",
    productList: [{ name: "End-of-Season Kurtis", quantity: 90, price: 1499 }],
  },
  {
    id: "ORD-2026-029",
    vendor: "RTS Wholesale Demo Account",
    date: "19 Apr 2026, 9:05 am",
    amount: "₹45,000",
    status: "Unfulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "25 Apr 2026",
    productList: [
      { name: "RTS Bulk Tees", quantity: 50, price: 450 },
      { name: "RTS Labels Pack", quantity: 50, price: 450 },
    ],
  },
  /* B2B Custom Orders tab — excluded from Bulk Orders list / KPIs via `customOrderStatus`. */
  {
    id: "ORD-CST-001",
    vendor: "Reliance Retail",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹50,499",
    status: "Unfulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "In Process",
    deadline: "21-Oct-2025",
    productList: [{ name: "Branded Uniform Rollout", quantity: 1, price: 50499 }],
  },
  {
    id: "ORD-CST-002",
    vendor: "Indigo Airlines",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹3,547.36",
    status: "Unfulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "In Process",
    deadline: "21-Oct-2025",
    productList: [{ name: "Crew Neck Tees — Logo", quantity: 1, price: 3547.36 }],
  },
  {
    id: "ORD-CST-003",
    vendor: "IIT Bombay",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹20,764",
    status: "Unfulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "In Process",
    deadline: "21-Oct-2025",
    productList: [{ name: "Event Merchandise Bundle", quantity: 1, price: 20764 }],
  },
  {
    id: "ORD-CST-004",
    vendor: "HDFC Bank",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹9,285.48",
    status: "Unconfirmed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "Pending Further Information",
    deadline: "21-Oct-2025",
    productList: [{ name: "Staff Jacket — Spec TBD", quantity: 1, price: 9285.48 }],
  },
  {
    id: "ORD-CST-005",
    vendor: "HDT Productions",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹3,547.36",
    status: "Unfulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "In Process",
    deadline: "21-Oct-2025",
    productList: [{ name: "Shoot Wardrobe Pack", quantity: 1, price: 3547.36 }],
  },
  {
    id: "ORD-CST-006",
    vendor: "Ola Electric",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹80,956",
    status: "Unconfirmed",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "Pending Further Information",
    deadline: "21-Oct-2025",
    productList: [{ name: "Field Team Apparel", quantity: 1, price: 80956 }],
  },
  {
    id: "ORD-CST-007",
    vendor: "Biocon",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹42,680",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "Fulfilled",
    deadline: "21-Oct-2025",
    productList: [{ name: "Lab Coats — Custom Sizes", quantity: 1, price: 42680 }],
  },
  {
    id: "ORD-CST-008",
    vendor: "Air India",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹20,764",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "Fulfilled",
    deadline: "21-Oct-2025",
    productList: [{ name: "Ground Staff Shirts", quantity: 1, price: 20764 }],
  },
  {
    id: "ORD-CST-009",
    vendor: "XYZ Retailers Pvt Ltd",
    date: "14 Jun 2025, 10:30 am",
    amount: "₹3,547.36",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2B",
    inventoryType: "ready_to_ship",
    delivery: "21 Oct 2025",
    customOrderStatus: "Fulfilled",
    deadline: "21-Oct-2025",
    productList: [{ name: "Private Label Capsule", quantity: 1, price: 3547.36 }],
  },
  {
    id: "ORD-2026-032",
    vendor: "Neha Joshi",
    date: "20 Apr 2026, 11:20 am",
    amount: "₹3,280",
    status: "Unfulfilled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "26 Apr 2026",
    productList: [
      { name: "Linen Blend Kurti", quantity: 1, price: 1899 },
      { name: "Printed Scarf", quantity: 1, price: 1381 },
    ],
  },
  {
    id: "ORD-2026-033",
    vendor: "Rohit Verma",
    date: "21 Apr 2026, 4:05 pm",
    amount: "₹7,650",
    status: "Partially Fulfilled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "28 Apr 2026",
    productList: [{ name: "Running Shoes - Mesh", quantity: 1, price: 7650 }],
  },
  {
    id: "ORD-2026-034",
    vendor: "Divya Krishnan",
    date: "22 Apr 2026, 9:40 am",
    amount: "₹1,890",
    status: "Unconfirmed",
    paymentStatus: "Pending",
    type: "B2C",
    delivery: "29 Apr 2026",
    returnStatus: "Approved",
    productList: [
      { name: "Kids School Shirt Pack", quantity: 2, price: 945 },
    ],
  },
  {
    id: "ORD-2026-035",
    vendor: "Manish Agarwal",
    date: "23 Apr 2026, 2:18 pm",
    amount: "₹12,400",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "27 Apr 2026",
    productList: [
      { name: "Leather Belt", quantity: 1, price: 2400 },
      { name: "Formal Oxford Shoes", quantity: 1, price: 10000 },
    ],
  },
  {
    id: "ORD-2026-036",
    vendor: "Pooja Nair",
    date: "24 Apr 2026, 10:55 am",
    amount: "₹2,199",
    status: "Fulfilled",
    paymentStatus: "Paid",
    type: "B2C",
    delivery: "28 Apr 2026",
    productList: [
      { name: "Varsity Jacket", quantity: 1, price: 2199 },
    ],
  },
];
